name: Build and Publish Container

on:
  push:
    branches:
      - main
    paths:
      - '.devcontainer/Dockerfile'
      - 'Project.toml'
      - 'Manifest.toml'
      - '.github/workflows/build-container.yml'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract Julia version from Manifest.toml
        id: julia-version
        run: |
          JULIA_VERSION=$(grep '^julia_version = ' Manifest.toml | sed 's/julia_version = "\(.*\)"/\1/')
          echo "version=${JULIA_VERSION}" >> $GITHUB_OUTPUT
          echo "Detected Julia version: ${JULIA_VERSION}"

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha,prefix={{branch}}-

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .devcontainer/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            JULIA_VERSION=${{ steps.julia-version.outputs.version }}
